version: "3"

services:
  server:
    build: 
      context: .
      target: prod
    env_file: .env
    environment:
      CORS_ALLOW_ORIGINS: '["http://localhost:8080","http://localhost:8081","http://localhost:5173"]'
    ports:
      - "8081:80"
