version: "3"

services:
  server:
    build:
      context: .
      target: dev 
    ports:
      - "8080:80"
      - "5678:5678"
    env_file: .env
    environment:
      CORS_ALLOW_ORIGINS: '["http://localhost:8080","http://localhost:5173"]'
    volumes:
      - type: bind
        source: src/
        target: /usr/app/src
        read_only: true

